# Remove when actionlint supports GitHub's self-repository syntax.
paths:
  .github/workflows/**/*.{yaml,yml}:
    ignore:
      - '^specifying action "\$/[^"@]+" in invalid format because ref is missing\.'
