packages:
  - "package"

blockExoticSubdeps: true

catalog:
  "@codecov/vite-plugin": 1.9.1
  rollup-plugin-sbom: 3.1.0
  dedent: 1.7.2
  "@sigstore/bundle": 4.0.0
  "@sigstore/core": 3.2.0
  "@types/node": 25.5.2
  "@vitest/coverage-istanbul": 4.1.2
  hysnappy: 1.1.1
  husky: 9.1.7
  markdownlint-cli2: 0.22.0
  oxfmt: 0.43.0
  oxlint: 1.58.0
  sigstore: 4.1.0
  typedoc: 0.28.18
  typedoc-theme-oxide: 0.2.5
  typescript: 6.0.2
  undici: 8.0.2
  vite: 8.0.3
  vite-plugin-dts: 5.0.0-beta.6
  vitest: 4.1.2
  zod: 4.3.6

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@oxfmt/*"

onlyBuiltDependencies: []

overrides:
  markdown-it: ">=14.1.1"

peerDependencyRules:
  allowedVersions:
    "rollup-plugin-sbom>vite": "8"

strictDepBuilds: true
