name: "Init Workflow"
description: "Defines central configurations and constants for workflows"
outputs:
  cache-key:
    description: "Cache key prefix for manual invalidation"
    value: "v1"
  env:
    description: "Environment variables"
    value: |
      {
        "CI": "true",
        "MISE_QUIET": "false",
        "MISE_LOCKED": "true"
      }
  test-coverage:
    description: "Globs for coverage reports"
    value: "packages/*/coverage/lcov.info"
  test-reports:
    description: "Globs for test reports"
    value: "packages/*/report.junit.xml"
  mise-version:
    description: "Mise version"
    value: "${{ steps.parse.outputs.mise-version }}"
runs:
  using: "composite"
  steps:
    - name: "Read mise version"
      id: "parse"
      shell: "bash"
      run: |
        echo "mise-version=$(cat .mise-version)" >> "$GITHUB_OUTPUT"
