name: "Upload Reports"
description: "Upload coverage and test reports to Codecov"
inputs:
  test-coverage:
    description: "Coverage report file path"
    required: true
  test-reports:
    description: "Test report file path"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Upload coverage to Codecov"
      uses: "codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f" # v7.0.0
      with:
        use_oidc: true
        report_type: "coverage"
        files: "${{ inputs.test-coverage }}"
    - name: "Upload test results to Codecov"
      uses: "codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f" # v7.0.0
      with:
        use_oidc: true
        report_type: "test_results"
        files: "${{ inputs.test-reports }}"
