name: "Upload Reports"
description: "Upload coverage and test reports to Codecov"
inputs:
  test-coverage:
    description: "Coverage report file path"
    required: true
  test-reports:
    description: "Test report file path"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Upload coverage to Codecov"
      uses: "codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe" # v5.5.4
      with:
        use_oidc: true
        report_type: "coverage"
        files: "${{ inputs.test-coverage }}"
    - name: "Upload test results to Codecov"
      uses: "codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe" # v5.5.4
      with:
        use_oidc: true
        report_type: "test_results"
        files: "${{ inputs.test-reports }}"
