name: "Upload Reports"
description: "Upload coverage and test reports to Codecov"
inputs:
  test-coverage:
    description: "Coverage report file path"
    required: true
  test-reports:
    description: "Test report file path"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Upload coverage to Codecov"
      uses: "codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2" # v6.0.0
      with:
        use_oidc: true
        report_type: "coverage"
        files: "${{ inputs.test-coverage }}"
    - name: "Upload test results to Codecov"
      uses: "codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2" # v6.0.0
      with:
        use_oidc: true
        report_type: "test_results"
        files: "${{ inputs.test-reports }}"
