name: "Build and publish"
on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}
permissions: {}
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    timeout-minutes: 15
    permissions:
      contents: "write" # for release creation
      id-token: "write" # for OIDC authentication
      attestations: "write" # for build provenance
    steps:
      - name: "Checkout"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6.0.2
        with:
          ref: "${{ github.ref }}"
          fetch-depth: 1
          persist-credentials: false
      - name: "Setup mise"
        uses: "jdx/mise-action@e79ddf65a11cec7b0e882bedced08d6e976efb2d" # v3.6.2
        with:
          version: "v2026.2.23"
          cache: false
      - name: "Bump version"
        run: 'pnpm run bump-version "${GITHUB_REF_NAME#v}"'
      - name: "Build"
        run: "pnpm run ci-build"
      - name: "Attest build provenance"
        uses: "actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32" # v4.1.0
        with:
          subject-path: "package.tar.gz"
      - name: "Create release"
        uses: "softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b" # v2.5.0
        with:
          files: "package.tar.gz"
          draft: false
  publish:
    name: "Publish"
    needs: "build"
    if: "needs.build.result == 'success'"
    runs-on: "ubuntu-latest"
    timeout-minutes: 15
    permissions:
      contents: "read" # to fetch code
      id-token: "write" # for OIDC authentication
    steps:
      - name: "Checkout"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6.0.2
        with:
          ref: "${{ github.ref }}"
          fetch-depth: 1
          persist-credentials: false
      - name: "Install latest Node.js with correct .npmrc"
        uses: "actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238" # v6.2.0
        with:
          node-version: "latest"
          check-latest: true
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false
      - name: "Update npm CLI"
        run: "npm install -g npm@latest"
      - name: "Download release artifact"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: 'gh release download "$GITHUB_REF_NAME" --pattern "package.tar.gz"'
      - name: "Publish to npmjs.org"
        run: 'npm publish "package.tar.gz" --access public --provenance'
